"""Add is_anomaly to expenses

Revision ID: a4d7cb520a2a
Revises: 14b4eae5be74
Create Date: 2026-04-25 19:53:17.008367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d7cb520a2a'
down_revision = '14b4eae5be74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anomaly', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('is_anomaly')

    # ### end Alembic commands ###
